pipeline{
    agent any
    tools{
        maven 'M2_HOME' 
   }

    stages{
        
        stage("sonnar scan"){
            steps{
                withSonarQubeEnv('sonarqube'){
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DonatienKT_week15-geo-app'
                }
            }
        }
        
        stage("maven"){
            steps {
                 sh 'mvn clean' 
                 sh 'mvn validate' 
                 sh 'mvn compile' 
                 sh 'mvn install' 
                 sh 'mvn test' 
                 sh 'mvn package'
            }
        }

        stage("upload artifact"){
            steps{
                sh 'curl -uadmin:AP6Q75MQXFQHggFWzUUVfo8HfEy -T \
                 target/bio*.jar \
                 "http://ec2-100-25-192-230.compute-1.amazonaws.com:8081/artifactory/devops-don/medical/biomedical_${BUILD_ID}.jar"'
            }
        }
        stage('docker login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 650959877739.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
    }   
}

