pipeline{
    agent any
    tools{
        maven 'M2_HOME'
   }

    stages{
        /*
        stage("sonnar scan"){
                        steps{
                withSonarQubeEnv('sonar')
                sh ''
            }
        }*/
        
        stage("maven"){
            steps {
                 sh 'mvn clean' 
                 sh 'mvn validate' 
                 sh 'mvn compile' 
                 sh 'mvn install' 
                 sh 'mvn test' 
                 sh 'mvn package'
            }
        }

        stage("upload artifact"){
            steps{
                sh 'curl -uadmin:AP6Q75MQXFQHggFWzUUVfo8HfEy -T \
                 target/bio*.jar \
                 "http://ec2-54-175-251-29.compute-1.amazonaws.com:8081/artifactory/devops-don/medical/biomedical_${BUILD_ID}.jar"'
            }
        }
    }   
}

